"""second m

Revision ID: 612fba922e5c
Revises: d449def599f1
Create Date: 2026-06-24 15:02:11.171700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612fba922e5c'
down_revision = 'd449def599f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.alter_column('close_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('close_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('close_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.alter_column('close_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
